### ISSUE TITLE
Question with the dataset

### ISSUE THREAD

**Issue by TikaToka** [GengzeZhou/NavGPT#1]
Hello, @GengzeZhou ,
first of all, thank you for sharing your work!

Normally, we use matterport simulator to run R2R or RxR, but your code seems to be not using the Matterport simulator. 

Can I ask how did you convert the dataset into no-simulator-needed dataset?

Thank you in advance!

**Comment by GengzeZhou** [comment]
Since NavGPT does not require visual input, we do not need the MP3D simulator for image rendering.

We pre-store the candidates' orientation at each viewpoint and implement a dummy simulator in MP3D at [env.py](https://github.com/GengzeZhou/NavGPT/blob/b3fc8a21b8a1f66b09dde833bcfc25767ef1962d/nav_src/env.py#L16C1-L80C28) for easy access (without building the Matterport3D simulator from source).

This simulator only serves for retrieving connectivity at the current location, teleporting agents from viewpoints, and recording the navigation trajectory.
